x = 'VFHKIRNEDLIFNESLGQGTFTKIFKGVRREVGDYGQLHETEVLLKVLDKAHRNYSESFFEAASMMSKLSHKHLVLNYGVCVCGDENILVQEFVKFGSLDTYLKKNKNCINILWKLEVAKQLAAAMHFLEENTLIHGNVCAKNILLIREEDRKTGNPPFIKLSDPGISITVLPKDILQERIPWVPPECIENPKNLNLATDKWSFGTTLWEICSGGDKPLSALDSQRKLQFYEDRHQLPAPKAAELANLINNCMDYEPDHRPSFRAIIRDLNSLF'
print len(x)
print x[124], x[241], x[258]


x = {1:10,2:20,3:30}

import operator
sorted_items = sorted(x.iteritems(), key=operator.itemgetter(0), reverse=True)

print sorted_items

sorted_items.append((4,40))
print sorted_items


print int(750.0)
